import './globals.css'
import type { Metadata } from 'next'
import { Libre_Franklin } from 'next/font/google'

const font = Libre_Franklin({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.className} text-xl bg-pale_blue/10`}>{children}</body>
    </html>
  )
}
